### ISSUE TITLE
Fix audio (`TypeError`) JS errors

### ISSUE THREAD

**Issue by cvan** [EFForg/spot_the_surveillance#87]
Fix autoplay issues introduced in PR #70. See [**this discussion**](https://github.com/EFForg/spot_the_surveillance/pull/70/files#r252493793) about these two JavaScript errors:

- `NotAllowedError: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`
- `TypeError: Argument 1 of BaseAudioContext.decodeAudioData does not implement interface ArrayBuffer.`

**Comment by cvan** [comment]
Since #90 is filed, I'm repurposing this issue for only the `TypeError` arraybuffer audio bugs.
